import Head from "next/head";
import { Inter } from "@next/font/google";
import Image from "next/image";
import Link from "next/link";
import { FaTshirt } from "react-icons/fa";
import { GiHoodie, GiCoffeeMug } from "react-icons/gi";
import { BsArrowRightShort } from "react-icons/bs";
import { TbSticker } from "react-icons/tb";

export default function Home() {
  return (
    <>
      <Head>
        <title>DevelopersWear - Look like developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen">
        <section className="text-gray-600 body-font">
          <div className="container px-5 py-24 mx-auto">
            <div className="flex flex-col text-center w-full mb-20">
              <h2 className="text-xs text-indigo-500 tracking-widest font-medium title-font mb-1">
                Short Catchy Line here
              </h2>
              <h1 className="sm:text-3xl text-2xl font-medium title-font text-gray-900">
                DevelopersWear - Look like developer
              </h1>
            </div>
            <div className="flex flex-wrap -m-4">
              <Link href={"/tshirts"} className="p-4 md:w-1/4">
                <div className="flex rounded-lg h-full bg-gray-100 p-8 flex-col hover:shadow-lg">
                  <div className="flex items-center mb-3">
                    <div className="w-8 h-8 mr-3 inline-flex items-center justify-center rounded-full bg-indigo-500 text-white flex-shrink-0">
                      <FaTshirt className="text-xl" />
                    </div>
                    <h2 className="text-gray-900 text-lg title-font font-medium">
                      TShirts
                    </h2>
                  </div>
                  <div className="flex-grow">
                    <p className="leading-relaxed text-base">
                      Lorem ipsum dolor sit amet consectetur adipisicing elit.
                      Voluptatem totam autem sint nulla tenetur.
                    </p>
                    <div className="mt-3 text-indigo-500 space-x-1 flex items-center">
                      <span>Buy Now</span>
                      <BsArrowRightShort className="text-xl" />
                    </div>
                  </div>
                </div>
              </Link>
              <Link href={"/hoodies"} className="p-4 md:w-1/4">
                <div className="flex rounded-lg h-full bg-gray-100 p-8 flex-col hover:shadow-lg">
                  <div className="flex items-center mb-3">
                    <div className="w-8 h-8 mr-3 inline-flex items-center justify-center rounded-full bg-indigo-500 text-white flex-shrink-0">
                      <GiHoodie className="text-xl" />
                    </div>
                    <h2 className="text-gray-900 text-lg title-font font-medium">
                      Hoodies
                    </h2>
                  </div>
                  <div className="flex-grow">
                    <p className="leading-relaxed text-base">
                      Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                      Ut harum enim quas molestias quidem.
                    </p>
                    <div className="mt-3 text-indigo-500 inline-flex items-center">
                      <span>Buy Now</span>
                      <BsArrowRightShort className="text-xl" />
                    </div>
                  </div>
                </div>
              </Link>
              <Link href={"/mugs"} className="p-4 md:w-1/4">
                <div className="flex rounded-lg h-full bg-gray-100 p-8 flex-col hover:shadow-lg">
                  <div className="flex items-center mb-3">
                    <div className="w-8 h-8 mr-3 inline-flex items-center justify-center rounded-full bg-indigo-500 text-white flex-shrink-0">
                      <GiCoffeeMug className="text-xl" />
                    </div>
                    <h2 className="text-gray-900 text-lg title-font font-medium">
                      Mugs
                    </h2>
                  </div>
                  <div className="flex-grow">
                    <p className="leading-relaxed text-base">
                      Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                      Id expedita animi impedit quo repudiandae.
                    </p>
                    <div className="mt-3 text-indigo-500 inline-flex items-center">
                      <span>Buy Now</span>
                      <BsArrowRightShort className="text-xl" />
                    </div>
                  </div>
                </div>
              </Link>
              <Link href={"/stickers"} className="p-4 md:w-1/4">
                <div className="flex rounded-lg h-full bg-gray-100 p-8 flex-col hover:shadow-lg">
                  <div className="flex items-center mb-3">
                    <div className="w-8 h-8 mr-3 inline-flex items-center justify-center rounded-full bg-indigo-500 text-white flex-shrink-0">
                      <TbSticker className="text-xl" />
                    </div>
                    <h2 className="text-gray-900 text-lg title-font font-medium">
                      Stickers
                    </h2>
                  </div>
                  <div className="flex-grow">
                    <p className="leading-relaxed text-base">
                      Lorem, ipsum dolor sit amet consectetur adipisicing elit.
                      Magnam necessitatibus deleniti sapiente delectus
                      voluptatum!
                    </p>
                    <div className="mt-3 text-indigo-500 inline-flex items-center">
                      <span>Buy Now</span>
                      <BsArrowRightShort className="text-xl" />
                    </div>
                  </div>
                </div>
              </Link>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
